Repository TRIE-Tech/mongol-api, pull requests merged in 2023-10, with the labels that each got.

#66 feat(mongol-api-web): changed favicon
  apps/mongol-api-web/public/logo.png
  apps/mongol-api-web/src/pages/_app.tsx
Labels: good first issue

#68 feat(mongol-api-action): added preview ready label to pr action
  .github/workflows/pull-request.yaml
  apps/mongol-api-web/src/pages/_app.tsx
Labels: preview ready, not mergeable

#72 fix(mongol-api): updated rest api links
  apps/mongol-api-web/src/features/docs/data/province.ts
  apps/mongol-api-web/src/features/home/Resources.tsx
  bun.lockb
  libs/mongol-api-data/src/lib/utils/index.ts
  tools/scripts/merge.sh
  tools/scripts/pull-request.sh
Labels: preview ready
